### ISSUE TITLE
support some sort of span link

### ISSUE THREAD

**Issue by c-cube** [c-cube/ocaml-trace#18]
A span (implicit or explicit) should be causally linkable to another span (or multiple other spans), either at creation time or with `add_data_to_span`. E.g. add `?link_to:span list -> …` to `add_data_to_span` and span creation functions.

very useful for OTEL and streaming. See https://opentelemetry.io/docs/concepts/signals/traces/#span-links .

**Comment by ELLIOTTCABLE** [comment]
Honestly, I'm leaning towards user-data for this — perhaps the best option is to add a `` `Span span `` type to the user-data? instead of a new function?

that leaves exactly _what_ semantics "referring to another span for some reason" has, up to the collector; and allows kinda 'naming' multiple other-related-spans with user-data keys.

**Comment by c-cube** [comment]
Interesting!! I need to think about it, but it's indeed nice to be able to say _why_ you link to another span. Or maybe a list of span (`` `Span of span list ``). Then backends can filter this out, or make it into span links…

**Comment by c-cube** [comment]
solved by the extension system!
